# Generated by Django 4.1.6 on 2023-02-08 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
                ('user_pw', models.CharField(max_length=200)),
                ('user_name', models.CharField(max_length=200)),
                ('user_email', models.TextField()),
                ('user_date', models.DateTimeField()),
            ],
        ),
    ]
