# Generated by Django 4.1.6 on 2023-02-08 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='user_info',
        ),
    ]
