# Generated by Django 4.1.6 on 2023-02-08 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0002_rename_user_user_info'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_info',
            new_name='asdf',
        ),
    ]
