# Generated by Django 4.1.6 on 2023-02-08 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0003_rename_user_info_asdf'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='asdf',
            new_name='user_info',
        ),
    ]
