# Generated by Django 4.1.6 on 2023-02-08 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0004_rename_asdf_user_info'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_info',
            new_name='user_info2',
        ),
    ]
